### ISSUE TITLE
Publish to npm 

### ISSUE THREAD

**Issue by azu** [textlint/gulp-textlint#2]
Would you consider publishing it to npm? 

Thanks.

**Comment by nakajmg** [comment]
It related to [this issues](https://github.com/nakajmg/gulp-textlint/issues/3).

We might want to publish after repository transfer completed :+1:

**Comment by azu** [comment]
I publish to npm and add @nakajmg as Collaborators!

![2015-11-07_01-20-51](https://cloud.githubusercontent.com/assets/19714/11002055/db88d738-84ed-11e5-9430-8317560c005d.jpg)

This issue is resolved :tada: 

Thanks again @nakajmg
