### ISSUE TITLE
Request for transfer: textlint organization

### ISSUE THREAD

**Issue by azu** [textlint/gulp-textlint#3]
Hi @nakajmg , I've created new organization [https://github.com/textlint](https://github.com/textlint) to help users to find related products easily, and I want you to transfer this project to textlint organization.

If you agree with me, please see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by nakajmg** [comment]
Hi @azu. 

> to help users to find related products easily,

That's a great :+1: 

> If you agree with me, please see Transferring a repository for details.

I completely agree with you :ok_woman:  and i saw "Transferring a repository" :eyes:

What should i do?

**Comment by azu** [comment]
Thanks. You do 5 step following link.

>  To transfer a repository to another user account:
> -- https://help.github.com/articles/transferring-a-repository/#to-transfer-a-repository-to-another-user-account

Please fill _"New owner’s GitHub username or organization name"_ by `textlint`.
- [GitHubのリポジトリを別のOwnerに引き渡す - Qiita](http://qiita.com/do7be/items/fa845240bc58b2153a44)

(and We sent invitation mail)

**Comment by nakajmg** [comment]
The repository transfer completed :tada:

**Comment by azu** [comment]
@nakajmg Thanks.
I'v pull request some test #6 and reflect new address to `package.json` #5
